<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rb_asset_archive"
 *
 * Auto generated by Extension Builder 2013-08-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Rolf Benz // Bild-Archiv',
	'description' => '',
	'category' => 'fe',
	'author' => 'Martin Lazar-Rudolf',
	'author_email' => 'martin@lazar-rudolf.de',
	'author_company' => 'Agentur Konitzer',
	'shy' => '0',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.5.5-6.2.99',
			'php' => '5.3.0-0.0.0',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>